### ISSUE TITLE
Player specific XP

### ISSUE THREAD

**Issue by FayeAlephNil** [elifoster/MC-SkillPoints#2] opened 2015-07-26 20:13 UTC
We are going to have to add in a way to make the XP player specific. I think the best way to do this is to just add an object (PlayerXP) onto the player.dat with all the data we need

**Comment by elifoster** [comment] 2015-07-26 23:43
Duplicate of "Saving XP per player and skill using NBT data" in #1. Closing. And as I said in IRC, that is going to happen last, after all of the XP generation code is finished. It'll be easiest to implement it then.

**Closed as completed** 2015-07-26 23:44 UTC
Labels: duplicate, enhancement
